// Generated by: gen
// TypeWriter: slice
// Directive: +gen on MyType

package main

import "errors"

// MyTypeSlice is a slice of type MyType. Use it where you would use []MyType.
type MyTypeSlice []MyType

// Average sums MyTypeSlice over all elements and divides by len(MyTypeSlice). See: http://clipperhouse.github.io/gen/#Average
func (rcv MyTypeSlice) Average() (MyType, error) {
	var result MyType

	l := len(rcv)
	if l == 0 {
		return result, errors.New("cannot determine Average of zero-length MyTypeSlice")
	}
	for _, v := range rcv {
		result += v
	}
	result = result / MyType(l)
	return result, nil
}
